version: '3'                                                                                       
services:                                                                                          
  web:                                                                                 
    build: .                                                                
    ports:                                                                                         
      - "5000:5000"                                                                                                           
    networks:                                                                                      
      - my_network                                                                                 
    depends_on:                                                                                    
      - db                                                                                         
  db:                                                                                              
    image: 'postgres:13.2-alpine'                                                                  
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=nftport_user
      - POSTGRES_PASSWORD=insecurepassword
      - POSTGRES_DB=nftport_test
    volumes:
      - db-data:/var/lib/postgresql/data # persist data even if container shuts down               
    networks:
      - my_network                                                                                 
volumes:                                                                                           
  db-data: # names volumes can be managed easier using docker-compose                                                                                                                                 
networks:                                                                                          
  my_network: 